FROM python:3.12-alpine

ENV PORT 1234
ENV WORKERS 123
ENV THREADS 456

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
ENV PIP_DISABLE_PIP_VERSION_CHECK 1

ENV APP_DIR /appdir
ENV APP_USER appuser

RUN adduser -DHs /sbin/nologin -h /dev/null -g ${APP_USER} ${APP_USER}

WORKDIR /tmp
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

WORKDIR ${APP_DIR}
COPY . .

USER ${APP_USER}
EXPOSE ${PORT}

CMD ["./run.sh"]
